#!/usr/bin/env python3
# -*- coding: utf-8  -*-

from faker import Faker, Factory
from faker.providers import internet 

fake = Faker('zh_CN')
print('## Faker 实例化对象生成虚拟数据 ##')
print('随机姓名 %s' % fake.name())
print('随机地址 %s' % fake.address())
print('随机文本 %s' % fake.text())
print('\n')

print('## Faker 工厂函数，使用providers  ##')
fake_internet = Factory.create()
fake_internet.add_provider(internet)
print('ipv4 私有地址 %s' % fake_internet.ipv4_private())

print('## Address 地址类信息 ##')
print('国家 %s' % fake.country())
print('城市 %s' % fake.city())
print('城市后缀 县、市 %s' % fake.city_suffix())
print('地址 %s' % fake.address())
print('街道 %s' % fake.street_address())
print('街道名 %s' % fake.street_name())
print('邮编 %s' % fake.postcode())
print('纬度 %s' % fake.latitude())
print('经度 %s' % fake.longitude())
print('\n')

print('## Person 人物类信息 ##')
print('姓名 %s' % fake.name())
print('姓 %s' % fake.last_name())
print('名 %s' % fake.first_name())
print('男性姓名 %s' % fake.name_male())
print('女性姓名 %s' % fake.name_female())
print('男性姓 %s' % fake.first_name_male())
print('男性名 %s' % fake.first_name_male())
print('\n')

print('## barcode 条码类信息 ##')
print('8位条码 %s' % fake.ean8())
print('13位条码 %s' % fake.ean13())
print('自定义位数条码 %s' % fake.ean(length=8))
print('\n')

print('## color 颜色 ##')
print('16进制表示的颜色 %s' % fake.hex_color())
print('css用的rgb颜色 %s' % fake.rgb_css_color())
print('表示rgb色的字符串 %s' % fake.rgb_color())
print('颜色的名字 %s' % fake.color_name())
print('安全的16进制色 %s' % fake.safe_hex_color())
print('安全的颜色名字 %s' % fake.safe_color_name())
print('\n')

print('## company 公司 ##')
print('公司名 %s' % fake.company())
print('公司名后缀 %s' % fake.company_suffix())
print('\n')

print('## credit_card 银行信用卡 ##')
print('卡号 %s' % fake.credit_card_number(card_type=None))
print('卡的提供者 %s' % fake.credit_card_provider(card_type=None))
print('卡的安全密码 %s' % fake.credit_card_security_code(card_type=None))
print('卡的有效期 %s' % fake.credit_card_expire())
print('卡的完整信息 %s' % fake.credit_card_full(card_type=None))
print('\n')

print('## currency 货币 ##')
print('货币代码 %s' % fake.currency_code())
print('\n')

print('## datetime 时间日期 ##')
print('随机日期时间 %s' % fake.date_time())
print('iso8601标准输出的日期 %s' % fake.iso8601())
print('本月的某个日期 %s' % fake.date_time_this_month(before_now=True, after_now=False, tzinfo=None))
print('本年的某个日期 %s' % fake.date_time_this_year(before_now=True, after_now=False, tzinfo=None))
print('本年代内的某个日期 %s' % fake.date_time_this_decade(before_now=True, after_now=False, tzinfo=None))
print('本世纪一个日期 %s' % fake.date_time_this_century(before_now=True, after_now=False, tzinfo=None))
print('两个时间间的一个随机时间 %s' % fake.date_time_between(start_date='-30y', end_date='now', tzinfo=None))
print('时区 %s' % fake.timezone())
print('时间(可自定义格式) %s' % fake.time(pattern='%H:%M:%S'))
print('随机上午下午 %s' % fake.am_pm())
print('随机月份 %s' % fake.month())
print('随机月份名字 %s' % fake.month_name())
print('随机年 %s' % fake.year())
print('随机星期几 %s' % fake.day_of_week())
print('随机月中某一天 %s' % fake.day_of_month())
print('随机时间延迟 %s' % fake.time_delta())
print('随机日期对象 %s' % fake.date_object())
print('随机时间对象 %s' % fake.time_object())
print('随机UNIX时间戳 %s' % fake.unix_time())
print('随机日期 %s' % fake.date(pattern='%Y-%m-%d'))
print('公元后随机日期 %s' % fake.date_time_ad(tzinfo=None))
print('\n')

print('## file 文件 ##')
print('文件名(指定文件类型和后缀名)%s' % fake.file_name(category='image', extension='png'))
print('随机生成各类文件 %s' % fake.file_name())
print('文件后缀 %s' % fake.file_extension(category=None))
print('mime-type %s' % fake.mime_type(category=None))
print('\n')

print('## internet 互联网 ##')
print('ipv4地址 %s' % fake.ipv4(network=False))
print('ipv6地址 %s' % fake.ipv6(network=False))
print('uri路径 %s' % fake.uri_path(deep=None))
print('uri扩展名 %s' % fake.uri_extension())
print('uri %s' % fake.uri())
print('url %s' % fake.url())
print('图片url %s' % fake.image_url(width=None, height=None))
print('域名主体 %s' % fake.domain_word())
print('域名 %s' % fake.domain_name())
print('域名后缀 %s' % fake.tld())
print('用户名 %s' % fake.user_name())
print('浏览器头UA %s' % fake.user_agent())
print('MAC地址 %s' % fake.mac_address())
print('安全邮箱 %s' % fake.safe_email())
print('免费邮箱 %s' % fake.free_email())
print('公司邮箱 %s' % fake.company_email())
print('邮箱 %s' % fake.email())
print('\n')

print('## job 工作 ##')
print('工作职位 %s' % fake.job())
print('\n')

print('## lorem 乱数假文 ##')
print('随机生成一篇文章 %s' % fake.text(max_nb_chars=200))
print('随机单词 %s' % fake.word())
print('随机生成几个字  %s' % fake.words(nb=3))
print('随机生成一个句子 %s' % fake.sentence(nb_words=6, variable_nb_words=True))
print('随机生成几个句子 %s' % fake.sentences(nb=3))
print('随机生成一段文字(字符串)%s' % fake.paragraph(nb_sentences=3, variable_nb_sentences=True))
print('随机生成几段文字(列表) %s' % fake.paragraphs(nb=3))
print('\n')

print('## misc 杂项 ##')
print('随机二进制字符串(可指定长度) %s' % fake.binary(length=10))
print('随机语言代码 %s' % fake.language_code())
print('随机md5, 16进制字符串 %s' % fake.md5(raw_output=False))
print('随机sha1, 16进制字符串 %s' % fake.sha1(raw_output=False))
print('随机sha256, 16进制字符串 %s' % fake.sha256(raw_output=False))
print('随机真假值(True,False 各50%%) %s' % fake.boolean(chance_of_getting_true=50))
print('随机真假值和null %s' % fake.null_boolean())
print('随机密码(可指定密码策略) %s' % fake.password(length=10, special_chars=True, digits=True, upper_case=True, lower_case=True))
print('随机本地语言代码 %s' % fake.locale())
print('随机uuid %s' % fake.uuid4())
print('\n')

print('## phone_number 电话号码 ##')
print('随机手机号码 %s' % fake.phone_number())
print('随机运营商号段，手机号码前三位 %s' % fake.phonenumber_prefix())
print('\n')

print('## python 数据 ##')
print('随机 int %s' % fake.pyint())
print('随机浮点数 %s' % fake.pyfloat(left_digits=None, right_digits=None, positive=False))
print('随机高精度浮点数 %s' % fake.pydecimal(left_digits=None, right_digits=None, positive=False))
print('随机字符串(可指定长度) %s' % fake.pystr(min_chars=None, max_chars=20))
print('随机 bool 值 %s' % fake.pybool())
print('随机 iterable %s' % (fake.pyiterable(nb_elements=10, variable_nb_elements=True), ))
print('随机生成一个 list  %s' % fake.pylist(nb_elements=10, variable_nb_elements=True))
print('随机字典  %s' % fake.pydict(nb_elements=10, variable_nb_elements=True))
print('随机 set %s' % fake.pyset(nb_elements=10, variable_nb_elements=True))
print('随机 tuple %s' % (fake.pytuple(nb_elements=10, variable_nb_elements=True), ))
print('随机生成3个有10个元素的python数据结构 %s' % (fake.pystruct(), ))
print('\n')

print('## profile 人物描述信息 ##')
print('人物描述信息：姓名、性别、地址、公司等 %s' % fake.profile(fields=None, sex=None))
print('人物精简信息 %s' % (fake.simple_profile(sex="m"), ))
print('\n')

print('## ssn 社会安全码(身份证)##')
print('随机生成身份证号(18位) %s' % fake.ssn())
print('\n')

print('## user_agent 浏览器头 ##')
print('伪造UA %s' % fake.user_agent())
print('伪造操作系统 %s' % fake.linux_platform_token())
print('伪造处理器核心 %s' % fake.linux_processor())
print('伪造windows平台 %s' % fake.windows_platform_token())
print('伪造mac平台 %s' % fake.mac_platform_token())
print('伪造mac处理器 %s' % fake.mac_processor())
print('伪造浏览器 %s\n\t%s\n\t%s\n\t%s\n\t%s' % (
    fake.internet_explorer(), 
    fake.opera(), 
    fake.firefox(), 
    fake.safari(), 
    fake.chrome()
))
print('\n')