"""添加 post body_html 字段 

Revision ID: 84936164000b
Revises: bf0b78c6cce2
Create Date: 2018-11-25 07:03:07.530189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84936164000b'
down_revision = 'bf0b78c6cce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
