"""修正评论表 添加timestamp

Revision ID: 869333ae249d
Revises: df91f208a1d9
Create Date: 2018-11-26 08:58:49.335589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869333ae249d'
down_revision = 'df91f208a1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
